using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using Google.Protobuf;
using Google.Protobuf.Reflection;
using Microsoft.Extensions.Logging;

namespace PaperBoy.Core.ProtoParsing;

public partial class JsonParser
{
    private const short RecursionLimit = 25;
    private readonly ILogger<JsonParser> _logger;

    public JsonParser(ILogger<JsonParser> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Reads bytes from proto descriptor generated by protoc-util. Returns JSON-like string represented original proto with stubbed values.
    /// </summary>
    /// <param name="protoDescriptor">Proto descriptor in bytes.</param>
    /// <returns>Proto contract as JSON-string.</returns>
    public string ParseToJsonWithStub(byte[] protoDescriptor)
    {
        FileDescriptorSet fileDescriptorSet = FileDescriptorSet.Parser.ParseFrom(protoDescriptor);

        IReadOnlyList<FileDescriptor> fileDescriptor =
            FileDescriptor.BuildFromByteStrings(fileDescriptorSet.File.Select(x => x.ToByteString()));

        StringBuilder sb = new StringBuilder().AppendLine("{");
        foreach (FileDescriptor descriptor in fileDescriptor)
        {
            if (descriptor.Services.Count > 0)
            {
                foreach (ServiceDescriptor service in descriptor.Services)
                {
                    if (_logger.IsEnabled(LogLevel.Debug))
                    {
                        LogServiceFullName(service.FullName);
                    }
                    sb.Append("\"").Append(service.FullName).Append("\"").AppendLine(":").AppendLine("{");

                    foreach (MethodDescriptor method in service.Methods)
                    {
                        sb.Append("\"").Append(method.Name).Append("\"").Append(":").AppendLine("{");

                        sb.Append("\"").Append(method.InputType.FullName).Append("\"").Append(":");
                        object sampleRequest = CreateDefaultMessage(method.InputType);
                        sb.Append(JsonSerializer.Serialize(sampleRequest)).AppendLine(",");

                        sb.Append("\"").Append(method.OutputType.FullName).Append("\"").Append(":");
                        object sampleResponse = CreateDefaultMessage(method.OutputType);
                        sb.Append(JsonSerializer.Serialize(sampleResponse)).AppendLine(",");
                        sb.AppendLine("},");
                    }
                    sb.AppendLine("}");
                }
            }
            else
            {
                if (_logger.IsEnabled(LogLevel.Debug))
                {
                    _logger.LogDebug(
                        "No service definitions was found in descriptor. Trying to parse stand alone messages.");
                }

                foreach (MessageDescriptor message in descriptor.MessageTypes)
                {
                    CreateDefaultMessage(message);
                }
            }
        }

        return sb.AppendLine("}").ToString();
    }

    public string ParseToJson(byte[] protoDescriptor)
    {
        throw new NotImplementedException();
    }

    private static IMessage CreateDefaultMessageForClrTypes(MessageDescriptor descriptor)
    {
        var message = (IMessage)Activator.CreateInstance(descriptor.ClrType);

        foreach (FieldDescriptor field in descriptor.Fields.InDeclarationOrder())
        {
            object value = CreateDefaultValue(field, 0);

            if (field.IsRepeated)
            {
                var list = (IList)field.Accessor.GetValue(message);
                list.Add(value);
            }
            else
            {
                field.Accessor.SetValue(message, value);
            }
        }

        return message;
    }
   
    static object CreateDefaultMessage(MessageDescriptor descriptor, int recursionDepth = 0)
    {
        if (recursionDepth > RecursionLimit)
        {
            return null;
        }

        Dictionary<string, object> obj = new();

        foreach (FieldDescriptor field in descriptor.Fields.InDeclarationOrder())
        {
            object value = CreateDefaultValue(field, recursionDepth);

            if (field.IsRepeated)
            {
                obj[field.Name] = new List<object> { value };
            }
            else
            {
                obj[field.Name] = value;
            }
        }

        return obj;
    }

    private static object CreateDefaultValue(FieldDescriptor field, int depth)
    {
        switch (field.FieldType)
        {
            case FieldType.String:
                return "string value example";

            case FieldType.Int32:
            case FieldType.SInt32:
            case FieldType.SFixed32:
                return 123;

            case FieldType.Int64:
            case FieldType.SInt64:
            case FieldType.SFixed64:
                return 123456789L;

            case FieldType.UInt32:
            case FieldType.Fixed32:
                return 123u;

            case FieldType.UInt64:
            case FieldType.Fixed64:
                return 123456789UL;

            case FieldType.Bool:
                return true;

            case FieldType.Double:
                return 1.23;

            case FieldType.Float:
                return 1.23f;

            case FieldType.Bytes:
                return ByteString.CopyFromUtf8("bytes");

            case FieldType.Enum:
                return field.EnumType.Values.First().Number;

            case FieldType.Message:
                return CreateDefaultMessage(field.MessageType);

            default:
                return null;
        }
    }

    [LoggerMessage(LogLevel.Debug, "Method: {methodName}")]
    partial void LogMethodMethodName(string methodName);

    [LoggerMessage(LogLevel.Debug, "Service: {serviceFullName}")]
    partial void LogServiceFullName(string serviceFullName);

    [LoggerMessage(LogLevel.Debug, "Request Type: {inputTypeFullName}")]
    partial void LogRequestTypeInputTypeFullname(string inputTypeFullName);
}