// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: adder.proto

//import "models/models.proto";

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftOperand   int32                  `protobuf:"varint,1,opt,name=left_operand,json=leftOperand,proto3" json:"left_operand,omitempty"`
	RightOperand  int32                  `protobuf:"varint,2,opt,name=right_operand,json=rightOperand,proto3" json:"right_operand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommand) Reset() {
	*x = AddCommand{}
	mi := &file_adder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommand) ProtoMessage() {}

func (x *AddCommand) ProtoReflect() protoreflect.Message {
	mi := &file_adder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommand.ProtoReflect.Descriptor instead.
func (*AddCommand) Descriptor() ([]byte, []int) {
	return file_adder_proto_rawDescGZIP(), []int{0}
}

func (x *AddCommand) GetLeftOperand() int32 {
	if x != nil {
		return x.LeftOperand
	}
	return 0
}

func (x *AddCommand) GetRightOperand() int32 {
	if x != nil {
		return x.RightOperand
	}
	return 0
}

type AddCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommandResponse) Reset() {
	*x = AddCommandResponse{}
	mi := &file_adder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommandResponse) ProtoMessage() {}

func (x *AddCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommandResponse.ProtoReflect.Descriptor instead.
func (*AddCommandResponse) Descriptor() ([]byte, []int) {
	return file_adder_proto_rawDescGZIP(), []int{1}
}

func (x *AddCommandResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type AddManyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddManyCommand) Reset() {
	*x = AddManyCommand{}
	mi := &file_adder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddManyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddManyCommand) ProtoMessage() {}

func (x *AddManyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_adder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddManyCommand.ProtoReflect.Descriptor instead.
func (*AddManyCommand) Descriptor() ([]byte, []int) {
	return file_adder_proto_rawDescGZIP(), []int{2}
}

func (x *AddManyCommand) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_adder_proto protoreflect.FileDescriptor

const file_adder_proto_rawDesc = "" +
	"\n" +
	"\vadder.proto\x12\x05adder\"T\n" +
	"\n" +
	"AddCommand\x12!\n" +
	"\fleft_operand\x18\x01 \x01(\x05R\vleftOperand\x12#\n" +
	"\rright_operand\x18\x02 \x01(\x05R\frightOperand\",\n" +
	"\x12AddCommandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"(\n" +
	"\x0eAddManyCommand\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result2y\n" +
	"\x05Adder\x123\n" +
	"\x03Add\x12\x11.adder.AddCommand\x1a\x19.adder.AddCommandResponse\x12;\n" +
	"\aAddMany\x12\x15.adder.AddManyCommand\x1a\x19.adder.AddCommandResponseB\aZ\x05./apib\x06proto3"

var (
	file_adder_proto_rawDescOnce sync.Once
	file_adder_proto_rawDescData []byte
)

func file_adder_proto_rawDescGZIP() []byte {
	file_adder_proto_rawDescOnce.Do(func() {
		file_adder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adder_proto_rawDesc), len(file_adder_proto_rawDesc)))
	})
	return file_adder_proto_rawDescData
}

var file_adder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_adder_proto_goTypes = []any{
	(*AddCommand)(nil),         // 0: adder.AddCommand
	(*AddCommandResponse)(nil), // 1: adder.AddCommandResponse
	(*AddManyCommand)(nil),     // 2: adder.AddManyCommand
}
var file_adder_proto_depIdxs = []int32{
	0, // 0: adder.Adder.Add:input_type -> adder.AddCommand
	2, // 1: adder.Adder.AddMany:input_type -> adder.AddManyCommand
	1, // 2: adder.Adder.Add:output_type -> adder.AddCommandResponse
	1, // 3: adder.Adder.AddMany:output_type -> adder.AddCommandResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adder_proto_init() }
func file_adder_proto_init() {
	if File_adder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adder_proto_rawDesc), len(file_adder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adder_proto_goTypes,
		DependencyIndexes: file_adder_proto_depIdxs,
		MessageInfos:      file_adder_proto_msgTypes,
	}.Build()
	File_adder_proto = out.File
	file_adder_proto_goTypes = nil
	file_adder_proto_depIdxs = nil
}
